export const WHITELIST_URLS = [
    '/api/v1/verify/apikey/',
    '/api/v1/chatflows/apikey/',
    '/api/v1/public-chatflows',
    '/api/v1/public-chatbotConfig',
    '/api/v1/prediction/',
    '/api/v1/vector/upsert/',
    '/api/v1/node-icon/',
    '/api/v1/components-credentials-icon/',
    '/api/v1/chatflows-streaming',
    '/api/v1/chatflows-uploads',
    '/api/v1/openai-assistants-file/download',
    '/api/v1/feedback',
    '/api/v1/leads',
    '/api/v1/get-upload-file',
    '/api/v1/ip',
    '/api/v1/ping',
    '/api/v1/version',
    '/api/v1/attachments',
    '/api/v1/metrics',
    '/api/v1/nvidia-nim',
    '/api/v1/image-proxy',
    // 前端页面需要的 API（开发模式下允许访问）
    '/api/v1/chatflows',
    '/api/v1/agentflows',
    '/api/v1/marketplaces',
    '/api/v1/tools',
    '/api/v1/assistants',
    '/api/v1/credentials',
    '/api/v1/variables',
    '/api/v1/apikey',
    '/api/v1/document-store',
    '/api/v1/nodes',
    '/api/v1/node-configs',
    '/api/v1/node-custom-function',
    '/api/v1/openai-assistants',
    '/api/v1/chatmessage',
    '/api/v1/stats',
    '/api/v1/auth',
    '/api/v1/usage-stats',
    '/api/v1/quota',
    '/api/v1/template-market',
    '/api/v1/model-evaluation',
    '/api/v1/chat-history',
    '/api/v1/system-config',
    '/api/v1/workflow-generator'
]

export const OMIT_QUEUE_JOB_DATA = ['componentNodes', 'appDataSource', 'sseStreamer', 'telemetry', 'cachePool']

export const INPUT_PARAMS_TYPE = [
    'asyncOptions',
    'asyncMultiOptions',
    'options',
    'multiOptions',
    'datagrid',
    'string',
    'number',
    'boolean',
    'password',
    'json',
    'code',
    'date',
    'file',
    'folder',
    'tabs'
]
